services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=contract_analyzer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.4
    restart: always
    ports:
      - "6379:6379"
