FROM node:22-alpine AS build

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/api/package.json apps/api/package.json

RUN pnpm install --frozen-lockfile

COPY apps/api apps/api

RUN pnpm --filter=api db:generate
RUN pnpm --filter=api build

FROM node:22-alpine AS runtime

WORKDIR /app

RUN corepack enable

COPY --from=build /app /app

ENV NODE_ENV=production
ENV UPLOAD_DIR=/app/apps/api/uploads

RUN mkdir -p /app/apps/api/uploads

EXPOSE 8000

CMD ["pnpm", "--filter=api", "start"]
